version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: store_postgres_dev
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d store_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: