# Generated by Django 5.2.6 on 2025-09-19 01:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("general_transaction", "Transacción General"),
                    ("papeleria_sale", "Venta de Papelería"),
                    ("bank_operation", "Operación Bancaria"),
                    ("commission_income", "Ingreso por Comisiones"),
                    ("expense_operational", "Gasto Operacional"),
                    ("expense_supplies", "Gasto en Suministros"),
                    ("cash_adjustment", "Ajuste de Caja"),
                    ("other_income", "Otros Ingresos"),
                    ("other_expense", "Otros Gastos"),
                ],
                default="general_transaction",
                max_length=25,
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="CashRegisterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Inicial"
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Final"
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Ingresos"
                    ),
                ),
                (
                    "total_outcome",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Egresos"
                    ),
                ),
                (
                    "total_commissions",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Comisiones"
                    ),
                ),
                (
                    "papeleria_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ingresos Papelería",
                    ),
                ),
                (
                    "bank_operations_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ingresos Operaciones Bancarias",
                    ),
                ),
                (
                    "commission_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ingresos por Comisiones",
                    ),
                ),
                (
                    "general_transactions_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ingresos Transacciones Generales",
                    ),
                ),
                (
                    "other_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Otros Ingresos",
                    ),
                ),
                (
                    "cash_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Efectivo",
                    ),
                ),
                (
                    "transfer_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Transferencias",
                    ),
                ),
                (
                    "card_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Tarjetas",
                    ),
                ),
                (
                    "other_payment_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Otros Métodos de Pago",
                    ),
                ),
                (
                    "physical_cash_count",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Conteo Físico de Efectivo",
                    ),
                ),
                (
                    "cash_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Diferencia en Efectivo",
                    ),
                ),
                (
                    "transaction_count",
                    models.IntegerField(
                        default=0, verbose_name="Número de Transacciones"
                    ),
                ),
                (
                    "shift_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duración del Turno (minutos)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas del Cierre"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_register",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_report",
                        to="caja.cashregister",
                        verbose_name="Caja Registradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Cierre de Caja",
                "verbose_name_plural": "Reportes de Cierre de Caja",
                "ordering": ["-created_at"],
            },
        ),
    ]
